### ISSUE TITLE
Killed for the long recording 

### ISSUE THREAD

**Issue by Ylw2014** [nomadkaraoke/python-audio-separator#120]
GPU memory will be OOM  when the recording time is too long ,for example 1 ~2 hours, any update plan for this scenerio? 

by the way, great job! great work!

**Comment by beveradb** [comment]
I have no plan to solve that as it's well outside of my own use case, sorry! You can try other models, or try changing the parameters to use a different batch size etc. - but depending on which model architecture you're using it may also have some kinda memory leak which might be causing the issue.

You can also always chunk your input audio into smaller clips (e.g. using ffmpeg), separate each smaller segment, then join the outputs!

If you decide you want to improve `audio-separator` to make it handle larger input files more gracefully like this yourself, PRs are welcome :)
