### ISSUE TITLE
Separate voices from a vocal track?

### ISSUE THREAD

**Issue by lyubomyr-shaydariv** [nomadkaraoke/python-audio-separator#121]
Hi!

I use the tool a lot to find kind of hidden stuff in audio tracks. Say, if vocals are separated, some instruments sound much more clear in the background. This especially applies for distorted/overdriven guitars or synths for rock/metal or electronic/industrial music with vocals overlapping the instruments.

However, some vocal samples are hard to identify. Let's say background vocals or vocal samples can be heard mixed with the foreground vocals even without audio tracks isolated. The audio separator obviously can strip instrumentals making vocals or vocal samples more identifiable especially for vocals remaining in the vocals track background.

Just wondering, is it possible to split the vocal track to voices?

**Comment by beveradb** [comment]
Hello! :) 
That's cool - I definitely love listening to the separated instrumentals from songs I know well, it's like getting to experience them in a totally new way!

Hmm, I'm not sure I totally understand what you're hoping for but there are models specifically designed to separate lead vocals from backing vocals which might be worth trying, e.g. 
- `mel_band_roformer_karaoke_aufr33_viperx_sdr_10.1956.ckpt`
- `UVR_MDXNET_KARA_2.onnx`
- `UVR-BVE-4B_SN-44100-1.pth`

and it might be worth trying a model which separates more than just instrumental/vocals (e.g. drums, bass, guitar, "other"):
- `htdemucs_6s.yaml`

you may also want to try the de-noise or de-crowd models, e.g. 
- `mel_band_roformer_crowd_aufr33_viperx_sdr_8.7144.ckpt`
- `denoise_mel_band_roformer_aufr33_sdr_27.9959.ckpt`

If you're able to send a test audio file, I'll run it through a few things and see what I can produce for you!

**Comment by lyubomyr-shaydariv** [comment]
Sorry for the vague question above, and thank you very much for suggesting the models! This would definitely help exploring audio stuff more effective.

So, there's a [song](https://www.youtube.com/watch?v=myJYGOKN55k). If you listen to the part from 1:09 to 1:40, you can hear mainly three components: the instrumental, the leading vocals and a voice sample that is barely legible and what I want to explore.

I merely downloaded a lossy .opus file right from YouTube as I guess it should not make a significant difference comparing to lossless audio. Using the default model `model_mel_band_roformer_ep_3005_sdr_11` two files are separated to **instrumental** and **leading vocals with voice_sample**. Now the voice is more legible but still covered with the leading vocals. That's really awesome, because I didn't believe the tool can "hear" it and interpret it as vocals too. Testing the models you suggested, the first is `mel_band_roformer_karaoke_aufr33_viperx_sdr_10` and it splits the input file to **instrumental with voice sample** and **leading vocals**. This is just awesome, because the vocal sample "floats" from the vocal part to instrumental part and vice versa, so I can subtract the channels almost by any audio editor. But what if the subtraction can be done by using Audio Separator only? Here is what I did:

```
[INPUT]
| (model_mel_band_roformer_ep_3005_sdr_11)
+-+-> [instrumental]
  +-> [leading vocals + voice sample)
      | (mel_band_roformer_karaoke_aufr33_viperx_sdr_10)
      +-> [leading vocals]
      +-> [voice sample] -- it sounds clean
                            and it is what I was looking for
```

It works! This is what I wanted by asking if vocals or voices in general can be separated. Yes, subtracting using an audio editor would be a more correct way, and maybe I'll test it later. Now I only need to find the source of the voice sample if it's well-known and probably transcribed elsewhere, or just consider it as a unique phrase reused or recorded for the song exclusively if nothing is found. :)

Maybe I was just lucky, but what would I get if there would be more voice samples, or more people singing, leading vocals and backing vocals? What would I do in more complex cases (if it's possible)?

**Comment by lyubomyr-shaydariv** [comment]
```shell
$ yt-dlp -x $VIDEO_ID
$ audio-separator -m htdemucs_6s.yaml $AUDIO_FILE
$ sox -m $AUDIO_BASS_FILE $AUDIO_DRUMS_FILE $AUDIO_VOCALS_FILE $NEW_AUDIO
```

☝🏻 is the new fun for me. 😅

**Comment by beveradb** [comment]
Closing as I think I've answered this as best as I know - if anyone finds (or creates) a model which can separate multiple different voices from a vocal track, please let me know as I'd love to integrate that into `audio-separator` 🙏
