### ISSUE TITLE
File Formats

### ISSUE THREAD

**Issue by Bebra777228** [nomadkaraoke/python-audio-separator#122]
Could you please tell me which file formats this tool supports?
It would be great to get a complete list =)

**Comment by beveradb** [comment]
It's kinda impossible to give a comprehensive list - it supports anything which [FFmpeg](https://www.ffmpeg.org/) supports, which is "pretty much everything" but in practice varies depending on how the user installed FFmpeg.

For example, if someone is using `audio-separator` on a system with `ffmpeg` installed with only free software (e.g. Fedora), without the ffmpeg compile time flags "--enable-gpl" and "--enable-nonfree", then they might not have access to encode to MP3 or Real Audio.

In my experience though, the vast majority of real ffmpeg installations are compiled with nonfree enabled, so anything on this huge list will be supported; https://www.ffmpeg.org/ffmpeg-codecs.html

**Comment by Bebra777228** [comment]
Thanks!
