### ISSUE TITLE
There is a performance difference between audio-separator and UVR_v5.6.0_setup_10_14.exe

### ISSUE THREAD

**Issue by OneSeven** [nomadkaraoke/python-audio-separator#129]
UVR GUI takes only 14 seconds, while audio-separator takes 21 seconds
I want to know what is the reason? How can I configure it?

![1111](https://github.com/user-attachments/assets/71fe7049-c783-436f-b344-641905468c4d)
![222](https://github.com/user-attachments/assets/64434147-12ef-46f8-a821-bde681dd70dc)
![3333](https://github.com/user-attachments/assets/761dd372-f229-40dd-9f03-10a02d39981d)

**Comment by beveradb** [comment]
There are so many differences in the overall code it's hard to say. 

You're very welcome to investigate, please share your results if you decide to figure it out! 🙏

**Comment by beveradb** [comment]
> audio-separator does not separate Vocals and Instrumental correctly.

I don't think that's a fair description, especially if you consider the results from different models.

The model you've chosen there (`UVR-MDX-NET-Inst_HQ_3.onnx`) is quite old and honestly not worth using these days - try the Roformer models e.g. `model_bs_roformer_ep_317_sdr_12.9755.ckpt`!

I tested your example file anyway, and you're right, there is a difference in the secondary (Vocals) stem for your input track and that `UVR-MDX-NET-Inst_HQ_3.onnx` model specifically.
However, the Instrumental stem sounds pretty clean to my ears, so considering `UVR-MDX-NET-Inst_HQ_3.onnx` is an instrumental focused model, I feel the results are good!

In the dropbox link below are the outputs from separating your track using UVR and audio-separator with the `UVR-MDX-NET-Inst_HQ_3.onnx` model, and from audio-separator with the `model_bs_roformer_ep_317_sdr_12.9755.ckpt` model - hopefully that demonstrates that there isn't a general issue with audio-separator!

**Comment by beveradb** [comment]
If vocals is your focus, I'd recommend trying one of the other models I mention in this comment:
https://github.com/nomadkaraoke/python-audio-separator/issues/121#issuecomment-2389911649

But overall, my original response still stands; you're very welcome to investigate and raise a PR if you see something worth fixing!
I can't guarantee that my code is identical to UVR or that it produces identical results to UVR, that was never the intention. Getting good enough results for the majority of use cases was my goal, and I believe I've achieved that as many people are now happily using this library on a day-to-day basis including me 😄

**Comment by beveradb** [comment]
> Due to work needs, I need to use the UVR-MDX-NET series model

If "work" is paid work, then either you or some other engineer working for your employer should do the work of finding and fixing whatever problem you have.

This is a free and open source software project - I do not get paid, and I have very limited free time to work on a wild goose chase for free for some other company.
You have full access to fix the problem yourself and raise a PR.

If you decide you or another engineer is going to try and tackle the problem you are having, I am happy to schedule a zoom/google meet call and talk you through the code, try to help you get up to speed.

**Comment by beveradb** [comment]
FYI @OneSeven to answer your previous question:

> In your experience which model is the best for separating Instrumental?

I've just written up a full answer to that, here: https://github.com/nomadkaraoke/python-audio-separator/discussions/133

Hope it helps! 🙏
