### ISSUE TITLE
Model Suggestions

### ISSUE THREAD

**Issue by shreeshailgan** [nomadkaraoke/python-audio-separator#136]
Amongst the list of all models supported, what is the best model to isolate background noises. I have an audio with a single person speaking and some background noise (cheers, applause, laughter, ambient noises etc). I'm not interested in the vocals, but isolating the background noises as best as possible.
Thanks.

**Comment by beveradb** [comment]
https://github.com/nomadkaraoke/python-audio-separator/discussions/133

**Comment by shreeshailgan** [comment]
Thanks. My bad, I did not find this query in the discussions section.
