### ISSUE TITLE
Problem recognizing gpu but only working with cpu

### ISSUE THREAD

**Issue by kbuwel** [nomadkaraoke/python-audio-separator#137]
conda install pytorch=*=*cuda* onnxruntime=*=*cuda* audio-separator -c pytorch -c conda-forge 
2024-10-17 02:46:58.559 - INFO - separator - ONNX Runtime GPU package installed with version: 1.19.2          
10-17 02:46:58.559 - INFO - separator - No hardware acceleration could be configured, running in CPU mode
My system is as follows.
5950x cpu, gtx1660 6gb
5600x, rtx3060oc 12gb 2x installed.

**Comment by beveradb** [comment]
Hello! That means you don't have a working CUDA environment.

There's a section in the README about this:
https://github.com/nomadkaraoke/python-audio-separator?tab=readme-ov-file#gpu--cuda-specific-installation-steps-with-pip

Good luck!
