### ISSUE TITLE
New Roformer Models

### ISSUE THREAD

**Issue by Bebra777228** [nomadkaraoke/python-audio-separator#145]
4 days ago in this release: [all_public_uvr_models](https://github.com/TRvlvr/model_repo/releases/tag/all_public_uvr_models), 3 new models were added:
- melband_roformer_instvoc_duality_v1.ckpt | [config](https://github.com/TRvlvr/application_data/blob/main/mdx_model_data/mdx_c_configs/config_melbandroformer_instvoc_duality.yaml)
- melband_roformer_instvox_duality_v2.ckpt | [config](https://github.com/TRvlvr/application_data/blob/main/mdx_model_data/mdx_c_configs/config_melbandroformer_instvoc_duality.yaml)
- melband_roformer_inst_v1.ckpt | [config](https://github.com/TRvlvr/application_data/blob/main/mdx_model_data/mdx_c_configs/config_melbandroformer_inst.yaml)

Will they be added to `audio-separator`?

**Comment by beveradb** [comment]
They already are! 

`audio-separator -l`

```
    "MDXC": {
        "MDX23C Model VIP: MDX23C-InstVoc HQ 2": {
            "MDX23C-8KFFT-InstVoc_HQ_2.ckpt": "model_2_stem_full_band_8k.yaml"
        },
        "MDX23C Model VIP: MDX23C_D1581": {
            "MDX23C_D1581.ckpt": "model_2_stem_061321.yaml"
        },
        "MDX23C Model: MDX23C-InstVoc HQ": {
            "MDX23C-8KFFT-InstVoc_HQ.ckpt": "model_2_stem_full_band_8k.yaml"
        },
        "Roformer Model: BS-Roformer-De-Reverb": {
            "deverb_bs_roformer_8_384dim_10depth.ckpt": "deverb_bs_roformer_8_384dim_10depth_config.yaml"
        },
        "Roformer Model: BS-Roformer-Viperx-1053": {
            "model_bs_roformer_ep_937_sdr_10.5309.ckpt": "model_bs_roformer_ep_937_sdr_10.5309.yaml"
        },
        "Roformer Model: BS-Roformer-Viperx-1296": {
            "model_bs_roformer_ep_368_sdr_12.9628.ckpt": "model_bs_roformer_ep_368_sdr_12.9628.yaml"
        },
        "Roformer Model: BS-Roformer-Viperx-1297": {
            "model_bs_roformer_ep_317_sdr_12.9755.ckpt": "model_bs_roformer_ep_317_sdr_12.9755.yaml"
        },
        "Roformer Model: MB-Roformer-Inst-v1 by Kim": {
            "melband_roformer_inst_v1.ckpt": "config_melbandroformer_inst.yaml"
        },
        "Roformer Model: MB-Roformer-InstVoc-Duality-v1 by Unwa": {
            "melband_roformer_instvoc_duality_v1.ckpt": "config_melbandroformer_instvoc_duality.yaml"
        },
        "Roformer Model: MB-Roformer-InstVoc-Duality-v2 by Unwa": {
            "melband_roformer_instvox_duality_v2.ckpt": "config_melbandroformer_instvoc_duality.yaml"
        },
        "Roformer Model: Mel-Roformer-Crowd-Aufr33-Viperx": {
            "mel_band_roformer_crowd_aufr33_viperx_sdr_8.7144.ckpt": "mel_band_roformer_crowd_aufr33_viperx_sdr_8.7144_config.yaml"
        },
        "Roformer Model: Mel-Roformer-Denoise-Aufr33": {
            "denoise_mel_band_roformer_aufr33_sdr_27.9959.ckpt": "denoise_mel_band_roformer_aufr33_sdr_27.9959_config.yaml"
        },
        "Roformer Model: Mel-Roformer-Denoise-Aufr33-Aggr": {
            "denoise_mel_band_roformer_aufr33_aggr_sdr_27.9768.ckpt": "denoise_mel_band_roformer_aufr33_aggr_sdr_27.9768_config.yaml"
        },
        "Roformer Model: Mel-Roformer-Karaoke-Aufr33-Viperx": {
            "mel_band_roformer_karaoke_aufr33_viperx_sdr_10.1956.ckpt": "mel_band_roformer_karaoke_aufr33_viperx_sdr_10.1956_config.yaml"
        },
        "Roformer Model: Mel-Roformer-Viperx-1143": {
            "model_mel_band_roformer_ep_3005_sdr_11.4360.ckpt": "model_mel_band_roformer_ep_3005_sdr_11.4360.yaml"
        }
    },
```

The way I built it is so it pulls in the UVR config dynamically so if something gets added to UVR, it is automatically available in `audio-separator` too, so no action required here 😄 

Thanks for the heads up though, I haven't tested those models so will give them a try later on :)

**Comment by Bebra777228** [comment]
Cool!
I'll try to run them now :)

**Comment by beveradb** [comment]
If they're good or offer something unique compared to the models I recommend already in this post, please share your findings 🙏 

https://github.com/nomadkaraoke/python-audio-separator/discussions/133

**Comment by Bebra777228** [comment]
## I'm not the best at writing test results, but here's what I found out for myself. :)

I compared the following models:
- `BS-Roformer-Viperx-1297`
- `Mel-Roformer-Viperx-1143`
- `MB-Roformer-Inst-v1 by Kim`
- `MB-Roformer-InstVoc-Duality-v1 by Unwa`
- `MB-Roformer-InstVoc-Duality-v2 by Unwa`

First off, I didn't hear much of a difference between `MB-Roformer-InstVoc-Duality-v1 by Unwa` and `MB-Roformer-InstVoc-Duality-v2 by Unwa`, so I'll talk about `MB-Roformer-InstVoc-Duality-v2 by Unwa`.

- **Model with the least noise:** `Mel-Roformer-Viperx-1143`
- **Model with the best vocal clarity:** `MB-Roformer-InstVoc-Duality-v2 by Unwa`

`MB-Roformer-InstVoc-Duality-v2 by Unwa` sounds a bit better than `BS-Roformer-Viperx-1297`, with clearer vocal separation, but it leaves some background noise.

`MB-Roformer-Inst-v1 by Kim` leaves a lot of noise, with instrumental sounds in the vocals and vice versa.

My personal ratings on a 10-point scale:
```
BS-Roformer-Viperx-1297                    - 8/10
Mel-Roformer-Viperx-1143                   - 7/10
MB-Roformer-Inst-v1 by Kim                 - 5/10
MB-Roformer-InstVoc-Duality-v1 by Unwa     - 9/10
MB-Roformer-InstVoc-Duality-v2 by Unwa     - 9/10
```

I'd give `MB-Roformer-InstVoc-Duality-v2 by Unwa` a 10 out of 10 if it didn't have background noise. I think it's a great model (personally for me)!

---

### I tested these models on just one audio file, so the results might be different on other audio.

**Comment by beveradb** [comment]
Nice, thanks for sharing! I'll check out the duality V2 model myself on some of my tracks later, if it's good enough to replace the current default model I might swap it out

**Comment by TomSuen** [comment]
> Nice, thanks for sharing! I'll check out the duality V2 model myself on some of my tracks later, if it's good enough to replace the current default model I might swap it out

how to load `melband_roformer_instvox_duality_v2.ckpt`, I got an error `RuntimeError: The size of tensor a (250047) must match the size of tensor b (485100) at non-singleton dimension 2`

**Comment by indiejoseph** [comment]
Searched around seems many people encountered this problem, this would happen if you apply it with a short audio file(<10s), but there still have no solution to fix it....
