### ISSUE TITLE
Problem with noise after audio separation

### ISSUE THREAD

**Issue by kbuwel** [nomadkaraoke/python-audio-separator#151]
[Untitled.zip](https://github.com/user-attachments/files/17717933/Untitled.zip)
https://github.com/user-attachments/assets/1dc34f0a-c272-4663-a2c6-9cf80bd15f1f

The command I entered was:
audio-separator a.mp4 --model_filename model_bs_roformer_ep_317_sdr_12.9755.ckpt --mdx_segment_size=512 --mdx_batch_size=10 --mdx_enable_denoise --mdx_overlap 0.6
My system is equipped with 2 rtx3060 12gb.
I also used UVR-DeNoise.pth to remove noise.
It is a sound that does not exist in the original, but the noise is not removed.
How do I remove the attached noise?
What kind of sound is the attached noise?

**Comment by ntamotsu** [comment]
I found that setting the `--amplification` option to a very small value (e.g., `--amplification=0.001`) resolves the issue.  
The default value for this option is 0.6.

**Comment by beveradb** [comment]
Thanks again for your PR - hopefully this is now resolved in `0.24.4` onwards 🤝
