### ISSUE TITLE
[Bug]: "Unsupported Model File" error for HTDemucs_6s

### ISSUE THREAD

**Issue by IneffableBunch** [nomadkaraoke/python-audio-separator#161]
### Describe the bug

`audio-separator --list`
returns:
`        "Demucs v4: htdemucs_6s": {
            "5c90dfd2-34c22ccb.th": "https://dl.fbaipublicfiles.com/demucs/hybrid_transformer/5c90dfd2-34c22ccb.th",
            "htdemucs_6s.yaml": "https://github.com/TRvlvr/model_repo/releases/download/all_public_uvr_models/htdemucs_6s.yaml"
        }`

but loading 5c90dfd2-34c22ccb.th does not work. 

### Have you searched for existing issues?  🔎

- [X] I have searched and found no existing issues.

### System Info

```shell
Operating System: Windows 
Python version: 3.10
Other...
```

**Comment by beveradb** [comment]
That's just a little inconsistency in the model list output because there are multiple sub-files for the demucs models (which could probably be tidied up in the `-l` output)

to use that demucs model use the model filename `"htdemucs_6s.yaml"` instead 😄

**Comment by Lixi20** [comment]
like this:
separator = Separator()
separator.load_model(model_filename='htdemucs_6s.yaml')
