### ISSUE TITLE
Problem with installing models

### ISSUE THREAD

**Issue by crexlight** [nomadkaraoke/python-audio-separator#39]
2024-02-07 15:13:31.123 - ERROR - separator - Failed to download file from https://github.com/TRvlvr/model_repo/releases/download/all_public_uvr_models/Kim_Vocal_2

As i see, it gives me 404 Not Found error https://github.com/TRvlvr/model_repo/releases/download/all_public_uvr_models/

**Comment by beveradb** [comment]
Gotcha @crexlight , sorry yeah it's confusing and I know i've changed the interface a bit with the latest version - sorry about that.
It helps make it more extensible / future proof (I'm working towards `audio-separator` being compatible with non-UVR models too eventually!)

There's also a new CLI param to list all of the currently supported model filenames by the way! 
`audio-separator --list_models`
