### ISSUE TITLE
Demucs models require Python version 3.10 or newer.

### ISSUE THREAD

**Issue by zhyqieqie** [nomadkaraoke/python-audio-separator#83]

**Comment by beveradb** [comment]
Thanks for the report! 
Feel free to raise a PR updating the docs or the Python version requirements. 

Honestly, Python 3.9 is 4 years old now, it's probably fair to drop support for it from `audio-separator completely`.

**Comment by beveradb** [comment]
I've removed support for Python 3.9 in `audio-separator` version `0.18.1` onwards, so I'm closing this.

If anyone really needs support for Python 3.9 these days I'd love to hear why! And I'd happily accept a PR which fails more gracefully for that python version e.g. if someone tries to use it for a model which doesn't work with that version
