### ISSUE TITLE
Request support for new model：denoise_mel_band_roformer_aufr33_aggr_sdr_27.9768.ckpt 、denoise_mel_band_roformer_aufr33_sdr_27.9959.ckpt ...

### ISSUE THREAD

**Issue by changqingonly** [nomadkaraoke/python-audio-separator#99]
1、the model repo：https://github.com/ZFTurbo/Music-Source-Separation-Training/releases
2、https://huggingface.co/anvuew/deverb_bs_roformer/tree/main

**Comment by beveradb** [comment]
Thanks for the heads up! Of course, if anyone else is willing to port the implementation over to `audio-separator` and raise a PR that would be greatly appreciated 🙇 

Otherwise, I can't promise when I'll get some free (un-allocated) hobby time to add this!

**Comment by beveradb** [comment]
I've just implemented and tested support for these new models:

- Mel-Roformer-Crowd-Aufr33-Viperx: `mel_band_roformer_crowd_aufr33_viperx_sdr_8.7144.ckpt`
- Mel-Roformer-Denoise-Aufr33: `denoise_mel_band_roformer_aufr33_sdr_27.9959.ckpt`
- Mel-Roformer-Denoise-Aufr33-Aggr: `denoise_mel_band_roformer_aufr33_aggr_sdr_27.9768.ckpt`
- Mel-Roformer-Karaoke-Aufr33-Viperx: `mel_band_roformer_karaoke_aufr33_viperx_sdr_10.1956.ckpt`

All are available and working in the latest version of `audio-separator`, version `0.21.0` 🎉 

Hopefully they're useful for you 😄
